# .github/workflows/deploy.yml

name: Deploy VitePress Site to Pages

on:
  push:
    branches: [main] # Otomatis jalan saat ada push ke branch main

# Izinkan workflow ini untuk membuat dan menulis ke branch gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # Folder yang akan di-deploy (hasil dari 'npm run docs:build')
          build_dir: docs/.vitepress/dist
          # Token untuk otentikasi
          token: ${{ secrets.GITHUB_TOKEN }}